#if DEBUG

import UIKit

final class DebugHandsViewController: UITableViewController {

    // MARK: - Public

    /// Called when the user picks a scenario. Passes the seed for the current player count.
    /// Pass `nil` to reset to random seed.
    var onSeedSelected: ((Int?) -> Void)?

    /// Number of players currently seated with bets (determines deal positions).
    var playerCount: Int = 1

    // MARK: - Scenario Model

    private struct Scenario {
        let title: String
        let subtitle: String
        let key: String
    }

    private struct Section {
        let title: String
        let scenarios: [Scenario]
    }

    private let sections: [Section] = [
        Section(title: "Reset", scenarios: [
            Scenario(title: "Random Seed", subtitle: "Reset to random deck (normal gameplay)", key: "random"),
        ]),
        Section(title: "Dealer", scenarios: [
            Scenario(title: "Blackjack", subtitle: "Dealer gets 21 on deal", key: "dealer_blackjack"),
            Scenario(title: "Ace Up", subtitle: "Dealer shows Ace (triggers insurance)", key: "dealer_ace_up"),
            Scenario(title: "10 Up", subtitle: "Dealer shows 10-value card", key: "dealer_10_up"),
        ]),
        Section(title: "Player (Seat 0)", scenarios: [
            Scenario(title: "Blackjack", subtitle: "Player gets 21 on deal", key: "player_blackjack"),
            Scenario(title: "Pair", subtitle: "Player gets two of same rank", key: "player_pair"),
            Scenario(title: "Hard 20", subtitle: "Player gets two 10-value cards", key: "player_hard_20"),
            Scenario(title: "Double 11", subtitle: "Player gets hard 11", key: "player_double_11"),
            Scenario(title: "Double 10", subtitle: "Player gets hard 10", key: "player_double_10"),
            Scenario(title: "Double 9", subtitle: "Player gets hard 9", key: "player_double_9"),
            Scenario(title: "Soft 17", subtitle: "Player gets Ace + 6", key: "player_soft_17"),
        ]),
        Section(title: "Combined", scenarios: [
            Scenario(title: "Both Blackjack", subtitle: "Dealer AND player get 21", key: "dealer_blackjack_player_blackjack"),
        ]),
    ]

    // Pre-computed seeds: [scenarioKey: [playerCount: seed]]
    // Generated by find_debug_seeds.js
    // Note: dealer_ace_up ensures Ace up with non-ten hole card (not blackjack)
    private static let debugSeeds: [String: [Int: Int]] = [
        "dealer_blackjack": [1: 842263072, 2: 2107627434, 3: 343816275, 4: 1514472367],
        "dealer_ace_up": [1: 2023959075, 2: 765177001, 3: 1788645527, 4: 898940862],
        "dealer_10_up": [1: 1697878755, 2: 204841831, 3: 1196556157, 4: 737112482],
        "player_blackjack": [1: 19160153, 2: 506539075, 3: 1565783613, 4: 1571767203],
        "player_pair": [1: 702836160, 2: 351817634, 3: 463319270, 4: 376648965],
        "player_hard_20": [1: 1101677087, 2: 1198176746, 3: 633403109, 4: 73288571],
        "player_double_11": [1: 1118871742, 2: 140711235, 3: 1653458046, 4: 260837137],
        "player_double_10": [1: 692276101, 2: 259264783, 3: 645809817, 4: 1003161547],
        "player_double_9": [1: 111731337, 2: 2102147097, 3: 1142649702, 4: 1828446738],
        "player_soft_17": [1: 809025087, 2: 119475077, 3: 329354941, 4: 1868251438],
        "dealer_blackjack_player_blackjack": [1: 286651523, 2: 683148489, 3: 1295900041, 4: 1593173909],
    ]

    // MARK: - Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Debug: Fixed Hands"
        navigationItem.rightBarButtonItem = UIBarButtonItem(
            barButtonSystemItem: .close, target: self, action: #selector(dismissSheet))
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "cell")

        let footer = UILabel()
        footer.text = "Seeds are pre-computed per player count.\nCurrent: \(playerCount) player(s)."
        footer.font = .systemFont(ofSize: 13)
        footer.textColor = .secondaryLabel
        footer.textAlignment = .center
        footer.numberOfLines = 0
        footer.frame = CGRect(x: 0, y: 0, width: 0, height: 60)
        tableView.tableFooterView = footer
    }

    @objc private func dismissSheet() {
        dismiss(animated: true)
    }

    // MARK: - UITableViewDataSource

    override func numberOfSections(in tableView: UITableView) -> Int {
        sections.count
    }

    override func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        sections[section].title
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        sections[section].scenarios.count
    }

    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
        let scenario = sections[indexPath.section].scenarios[indexPath.row]
        
        // Clear existing subviews
        cell.contentView.subviews.forEach { $0.removeFromSuperview() }
        
        let isRandom = scenario.key == "random"
        let hasSeed = isRandom || Self.debugSeeds[scenario.key]?[playerCount] != nil
        
        // Title label
        let titleLabel = UILabel()
        titleLabel.text = scenario.title
        titleLabel.font = .systemFont(ofSize: 17, weight: .medium)
        titleLabel.textColor = hasSeed ? .label : .tertiaryLabel
        titleLabel.translatesAutoresizingMaskIntoConstraints = false
        
        // Subtitle label
        let subtitleLabel = UILabel()
        if isRandom {
            subtitleLabel.text = scenario.subtitle
        } else {
            subtitleLabel.text = hasSeed ? scenario.subtitle : "No seed for \(playerCount) player(s)"
        }
        subtitleLabel.font = .systemFont(ofSize: 13)
        subtitleLabel.textColor = .secondaryLabel
        subtitleLabel.numberOfLines = 0
        subtitleLabel.translatesAutoresizingMaskIntoConstraints = false
        
        cell.contentView.addSubview(titleLabel)
        cell.contentView.addSubview(subtitleLabel)
        
        var constraints: [NSLayoutConstraint] = [
            titleLabel.leadingAnchor.constraint(equalTo: cell.contentView.leadingAnchor, constant: 16),
            titleLabel.topAnchor.constraint(equalTo: cell.contentView.topAnchor, constant: 12),
            titleLabel.trailingAnchor.constraint(lessThanOrEqualTo: cell.contentView.trailingAnchor, constant: -16),
            
            subtitleLabel.leadingAnchor.constraint(equalTo: cell.contentView.leadingAnchor, constant: 16),
            subtitleLabel.topAnchor.constraint(equalTo: titleLabel.bottomAnchor, constant: 4),
            subtitleLabel.trailingAnchor.constraint(lessThanOrEqualTo: cell.contentView.trailingAnchor, constant: -16),
        ]
        
        // Add card combination view for scenarios with fixed hands (not for random)
        if !isRandom && hasSeed, let cards = representativeCards(for: scenario.key) {
            let cardView = CardCombinationView()
            cardView.configure(cards: cards, odds: "")
            cardView.translatesAutoresizingMaskIntoConstraints = false
            
            cell.contentView.addSubview(cardView)
            
            constraints.append(contentsOf: [
                cardView.leadingAnchor.constraint(equalTo: cell.contentView.leadingAnchor, constant: 16),
                cardView.topAnchor.constraint(equalTo: subtitleLabel.bottomAnchor, constant: 8),
                cardView.trailingAnchor.constraint(lessThanOrEqualTo: cell.contentView.trailingAnchor, constant: -16),
                cardView.bottomAnchor.constraint(equalTo: cell.contentView.bottomAnchor, constant: -12)
            ])
        } else {
            constraints.append(
                subtitleLabel.bottomAnchor.constraint(equalTo: cell.contentView.bottomAnchor, constant: -12)
            )
        }
        
        NSLayoutConstraint.activate(constraints)
        
        cell.accessoryType = hasSeed ? .disclosureIndicator : .none
        cell.selectionStyle = hasSeed ? .default : .none
        return cell
    }
    
    // MARK: - Card Representation
    
    /// Returns representative cards for a scenario (for visual display)
    private func representativeCards(for scenarioKey: String) -> [(rank: PlayingCardView.Rank, suit: PlayingCardView.Suit)]? {
        switch scenarioKey {
        case "dealer_blackjack":
            return [(.king, .hearts), (.ace, .spades)]
        case "dealer_ace_up":
            return [(.ace, .hearts)]
        case "dealer_10_up":
            return [(.king, .hearts)]
        case "player_blackjack":
            return [(.ace, .hearts), (.king, .spades)]
        case "player_pair":
            return [(.ten, .hearts), (.ten, .diamonds)]
        case "player_hard_20":
            return [(.king, .hearts), (.queen, .spades)]
        case "player_double_11":
            return [(.five, .hearts), (.six, .clubs)]
        case "player_double_10":
            return [(.four, .hearts), (.six, .diamonds)]
        case "player_double_9":
            return [(.four, .hearts), (.five, .clubs)]
        case "player_soft_17":
            return [(.ace, .hearts), (.six, .diamonds)]
        case "dealer_blackjack_player_blackjack":
            return [(.king, .hearts), (.ace, .spades)]  // Dealer's hand
        default:
            return nil
        }
    }

    // MARK: - UITableViewDelegate

    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let scenario = sections[indexPath.section].scenarios[indexPath.row]
        
        if scenario.key == "random" {
            print("🐛 [Debug] Selected \"\(scenario.title)\" → reset to random seed")
            dismiss(animated: true) { [weak self] in
                self?.onSeedSelected?(nil)
            }
            return
        }
        
        guard let seed = Self.debugSeeds[scenario.key]?[playerCount] else { return }

        print("🐛 [Debug] Selected \"\(scenario.title)\" for \(playerCount) player(s) → seed \(seed)")
        dismiss(animated: true) { [weak self] in
            self?.onSeedSelected?(seed)
        }
    }
}

#endif
